name: iOS Build Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current branch and commit
        run: |
          git status
          git log --oneline -5

      - name: List root folder
        run: ls -l

      - name: List BLE_Scanner.xcodeproj content
        run: ls -lR BLE_Scanner.xcodeproj

      - name: Show first lines of project.pbxproj
        run: head -30 BLE_Scanner.xcodeproj/project.pbxproj

      - name: Check file encoding & line endings
        run: |
          file BLE_Scanner.xcodeproj/project.pbxproj
          grep -P '\r' BLE_Scanner.xcodeproj/project.pbxproj || echo "No CR (Windows) line endings found"

      - name: Display .gitignore
        run: cat .gitignore || echo ".gitignore not found"

      - name: Generate MQTTCredentials.plist
        run: |
          mkdir -p BLE_Scanner/BLE_Scanner
          cat <<EOF > ./BLE_Scanner/BLE_Scanner/MQTTCredentials.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>host</key>
              <string>${{ secrets.MQTT_HOST }}</string>
              <key>port</key>
              <integer>${{ secrets.MQTT_PORT }}</integer>
              <key>username</key>
              <string>${{ secrets.MQTT_USERNAME }}</string>
              <key>password</key>
              <string>${{ secrets.MQTT_PASSWORD }}</string>
          </dict>
          </plist>
          EOF

      # 如果你沒有用 CocoaPods 可以跳過這步
      # - name: Install dependencies
      #   run: cd BLE_Scanner && pod install

      - name: Clean workspace
        run: git clean -xfd
        
     - name: Select Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app
    
     - name: Check Xcode version
        run: xcodebuild -version

      - name: Build with xcodeproj
        run: |
          xcodebuild -project BLE_Scanner.xcodeproj \
                     -scheme BLE_Scanner \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     -derivedDataPath build \
                     clean build

      - name: Show xcodebuild error logs if failed
        if: failure()
        run: |
          echo "Xcode build failed, showing derived data logs:"
          find build -name "*.log" -exec head -50 {} \;
