- name: Generate MQTTCredentials.plist
  run: |
    cat <<EOF > ./BLE_Scanner/BLE_Scanner/MQTTCredentials.plist
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        <key>host</key>
        <string>${{ secrets.MQTT_HOST }}</string>
        <key>port</key>
        <integer>${{ secrets.MQTT_PORT }}</integer>
        <key>username</key>
        <string>${{ secrets.MQTT_USERNAME }}</string>
        <key>password</key>
        <string>${{ secrets.MQTT_PASSWORD }}</string>
    </dict>
    </plist>
    EOF
