name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode version (可選)
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Generate MQTTCredentials.plist
      run: |
        cat <<EOF > ./BLE_Scanner/BLE_Scanner/MQTTCredentials.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>host</key>
            <string>${{ secrets.MQTT_HOST }}</string>
            <key>port</key>
            <integer>${{ secrets.MQTT_PORT }}</integer>
            <key>username</key>
            <string>${{ secrets.MQTT_USERNAME }}</string>
            <key>password</key>
            <string>${{ secrets.MQTT_PASSWORD }}</string>
        </dict>
        </plist>
        EOF

    # 如果你沒有用 CocoaPods 可以跳過這步
    # - name: Install dependencies
    #   run: cd BLE_Scanner && pod install

    - name: Build with xcodeproj
      run: |
        xcodebuild -project BLE_Scanner.xcodeproj \
                   -scheme BLE_Scanner \
                   -sdk iphonesimulator \
                   -destination 'platform=iOS Simulator,name=iPhone 14' \
                   -derivedDataPath build \
                   clean build
